spring:
  profiles: dev

  devtools:
    remote:
      secret: 123
    restart:
      trigger-file: trigger.txt

  datasource:
    url: jdbc:h2:mem:storefront
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    queue:
      product-change-availability: product.change.availability.queue

warehouse:
  base-path: http://localhost:8080/warehouse
